apiVersion: v1 
kind: Pod

metadata: 
  name: nginx-dev
  namespace: roboshop-dev
  labels:
    environment: dev
    project: roboshop

spec:
  containers:
    - name: nginx 
      image: nginx
      ports:
        - containerPort: 80