apiVersion: v1 
kind: Service
metadata:
  name: service-demo
spec:
  selector:
    project: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 80 #servicePort
      targetport: 80 #containerport