apiVersion: v1 
kind: Service
metadata:
  name: nodeservice
spec:
  type: Nodeport
  selector:
    project: roboshop
    environment: development
    purpose: node-port
  ports:
  protocol: TCP
  port: 80
  targetPort: 80

