apiVersion: v1 
kind: Pod
metadata:
  name: node-pod 
  labels:
    project: roboshop 
    environment: development
    purpose: node-port
  spec: 
    containers:
      - name: nginx
        image: nginx
        
         