apiVersion: v1 
kind: Service
metadata:
  name: lb-demo
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    environment: development
    purpose: loadbalancer
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80
     nodePort: 30008

